import { v4 as uuid } from 'uuid';
import type { Task } from './types';

const now = Date.now();
const days = (n: number) => 1000 * 60 * 60 * 24 * n;

export const sampleTasks: Task[] = [
  {
    id: uuid(),
    title: 'Create onboarding flow',
    description: 'Design welcome screen and progressive profile setup.',
    status: 'scheduled',
    assignee: 'YiTing',
    tags: ['ux', 'product'],
    createdAt: now - days(12),
    dueDate: new Date(now + days(5)).toISOString(),
    priority: 'high',
  },
  {
    id: uuid(),
    title: 'Implement Kanban columns',
    description: 'Move tasks between Scheduled / In-Progress / Done.',
    status: 'in-progress',
    assignee: 'Alex',
    tags: ['frontend', 'nextjs'],
    createdAt: now - days(10),
    priority: 'medium',
  },
  {
    id: uuid(),
    title: 'Add localStorage persistence',
    description: 'Persist tasks and filter prefs to browser storage.',
    status: 'in-progress',
    assignee: 'Sam',
    tags: ['state'],
    createdAt: now - days(8),
    priority: 'high',
  },
  {
    id: uuid(),
    title: 'Testing plan',
    description: 'Happy-path flows + filter logic.',
    status: 'scheduled',
    assignee: 'Taylor',
    tags: ['qa'],
    createdAt: now - days(7),
    priority: 'low',
  },
  {
    id: uuid(),
    title: 'Task details page',
    description: 'Dynamic route with full task info and edit.',
    status: 'scheduled',
    assignee: 'YiTing',
    tags: ['routing'],
    createdAt: now - days(6),
  },
  {
    id: uuid(),
    title: 'Board responsiveness',
    description: 'Mobile-first columns → stacked list.',
    status: 'in-progress',
    assignee: 'Riley',
    tags: ['css', 'tailwind'],
    createdAt: now - days(5),
  },
  {
    id: uuid(),
    title: 'Bulk move done → archive (stretch)',
    description: 'Batch select, move to archive bucket.',
    status: 'scheduled',
    assignee: 'Jordan',
    tags: ['stretch'],
    createdAt: now - days(4),
  },
  {
    id: uuid(),
    title: 'Finish README',
    description: 'Tradeoffs + testing + time spent.',
    status: 'done',
    assignee: 'YiTing',
    tags: ['docs'],
    createdAt: now - days(3),
  },
  {
    id: uuid(),
    title: 'Filter by tag & assignee',
    description: 'Combine with free-text search.',
    status: 'done',
    assignee: 'Alex',
    tags: ['filters'],
    createdAt: now - days(2),
  },
  {
    id: uuid(),
    title: 'Empty/loading states',
    description: 'Meaningful placeholders + skeletons.',
    status: 'done',
    assignee: 'Sam',
    tags: ['ux'],
    createdAt: now - days(1),
  },
];
